### ISSUE TITLE
数码之家签到失败

### ISSUE THREAD

**Issue by hehewocao** [sadoneli/merlin380-qiandao#9]
感谢大神开发如此优秀的插件，数码之家的签到已知未能成功，为啥呢？账户密码已经确认无误了呀

**Comment by Carseason** [comment]
> 感谢大神开发如此优秀的插件，数码之家的签到已知未能成功，为啥呢？账户密码已经确认无误了呀

数码之家已经在服务器进行了验证，目前已经放弃了数码之家的签到

**Comment by wenbinhuang** [comment]
id="JD_sign" href="(.*)" onclick
按这个正则表达式能把签到链接取到，
请作者麻烦改下代码。
